# Default Values for Kinesis MCP Server

# Default Region
DEFAULT_REGION = 'us-west-2'

# Default values
DEFAULT_SHARD_COUNT = 1
DEFAULT_STREAM_LIMIT = 100
DEFAULT_GET_RECORDS_LIMIT = 10000

# Stream status
STREAM_STATUS_CREATING = 'CREATING'
STREAM_STATUS_ACTIVE = 'ACTIVE'
STREAM_STATUS_UPDATING = 'UPDATING'
STREAM_STATUS_DELETING = 'DELETING'

# Shared Error Handling Constants
MAX_STREAM_NAME_LENGTH = 128
MIN_STREAM_NAME_LENGTH = 1
MAX_STREAM_ARN_LENGTH = 2048
MIN_STREAM_ARN_LENGTH = 1
MAX_LIMIT = 10000
MIN_LIMIT = 1

# put_records Error Handling Constants
MAX_RECORDS = 500
MIN_RECORDS = 1

# get_records Error Handling Constants
MAX_LENGTH_SHARD_ITERATOR = 512
MIN_LENGTH_SHARD_ITERATOR = 1

# create_stream Error Handling Constants
STREAM_MODE_PROVISIONED = 'PROVISIONED'
STREAM_MODE_ON_DEMAND = 'ON_DEMAND'
DEFAULT_STREAM_MODE = STREAM_MODE_ON_DEMAND
MAX_TAGS_COUNT = 50
MAX_TAG_ENTRIES = 200
MAX_TAG_KEY_LENGTH = 128
MIN_TAG_KEY_LENGTH = 1
MAX_TAG_VALUE_LENGTH = 256
MIN_TAG_VALUE_LENGTH = 0
MAX_SHARDS_PER_STREAM = 500

# list_streams Error Handling Constants
MAX_EXCLUSIVE_START_STREAM_NAME_LENGTH = 128
MIN_EXCLUSIVE_START_STREAM_NAME_LENGTH = 1
MAX_NEXT_TOKEN_LENGTH = 1048576
MIN_NEXT_TOKEN_LENGTH = 1

# describe_stream_summary Error Handling Constants - only has shared Error Handling Constants
