# Default Values for Kinesis MCP Server

# Stream modes
STREAM_MODE_PROVISIONED = 'PROVISIONED'
STREAM_MODE_ON_DEMAND = 'ON_DEMAND'

# Default values
DEFAULT_SHARD_COUNT = 1
DEFAULT_STREAM_LIMIT = 100

# Stream status
STREAM_STATUS_CREATING = 'CREATING'
STREAM_STATUS_ACTIVE = 'ACTIVE'
STREAM_STATUS_UPDATING = 'UPDATING'
STREAM_STATUS_DELETING = 'DELETING'

# Maximum values (from TODOs)
MAX_SHARDS_PER_REGION = 500
MAX_TAGS = 50

# Default Region
DEFAULT_REGION = 'us-west-2'
